name: 'sales_medallion'
version: '1.0.0'
config-version: 2

profile: 'sales_medallion'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  sales_medallion:
    +quote_columns: false

models:
  sales_medallion:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: view
      +schema: silver
    marts:
      core:
        +materialized: table
        +schema: gold
